name: Build and Upload Canary
on:
  # Allows you to run this manually from the Forgejo UI
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. FIX: Install system dependencies BEFORE setup-bun
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip libstdc++6

      - name: Setup Bun
        uses: https://github.com/oven-sh/setup-bun@v2
        with:
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Canary
        run: bun run build:canary

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: canary-build
          # Replace 'dist' with your actual output folder (e.g., 'out' or 'build')
          path: artifacts/
          retention-days: 7