name: Build and Upload Canary
on:
  # Allows you to run this manually from the Forgejo UI
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # This is the critical missing step
      - name: Setup Node.js (Required for setup-bun v2)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Bun
        uses: https://github.com/oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Canary
        run: bun run build:canary

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: canary-build
          # Replace 'dist' with your actual output folder (e.g., 'out' or 'build')
          path: artifacts/
          retention-days: 7