// ES-DE to emulator JS mapping
// TODO: use the retroarch cores based on ES-DE
export const cores: Record<string, string> = {
    "atari5200": "atari5200",
    "virtualboy": "vb",
    "nds": "nds",
    "arcade": "arcade",
    "nes": "nes",
    "gb": "gb",
    "gbc": "gb",
    "colecovision": "coleco",
    "mastersystem": "segaMS",
    "megadrive": "segaMD",
    "gamegear": "segaGG",
    "segacd": "segaCD",
    "sega32x": "sega32x",
    "genesis": "sega",
    "mark3": "sega",
    "megacd": "sega",
    "megacdjp": "sega",
    "megadrivejp": "sega",
    "sg-1000": "sega",
    "atarilynx": "lynx",
    "mame": "mame",
    "ngp": "ngp",
    "supergrafx": "pce",
    "pcfx": "pcfx",
    "psx": "psx",
    "wonderswan": "ws",
    "gba": "gba",
    "n64": "n64",
    "3do": "3do",
    "psp": "psp",
    "atari7800": "atari7800",
    "snes": "snes",
    "atari2600": "atari2600",
    "atarijaguar": "jaguar",
    "saturn": "segaSaturn",
    "amiga": "amiga",
    "c64": "c64",
    "c128": "c128",
    "pet": "pet",
    "plus4": "plus4",
    "vic20": "vic20",
    "dos": "dos"
};