export declare global
{
    interface Window
    {
        EJS_emulator: any,
        EJS_player: string,
        EJS_gameUrl: string,
        EJS_pathtodata: string,
        EJS_language: string,
        EJS_disableAutoLang: boolean,
        EJS_paths: Record<string, string>,
        EJS_volume: number,
        EJS_gameName: string,
        EJS_cheats: string[][],
        EJS_fullscreenOnLoaded: boolean,
        EJS_startOnLoaded: boolean,
        EJS_core: string,
        EJS_lightgun: boolean,
        EJS_biosUrl: string,
        EJS_color: string,
        EJS_AdUrl: string,
        EJS_AdMode: string,
        EJS_AdTimer: number,
        EJS_AdSize: number,
        EJS_alignStartButton: boolean,
        EJS_VirtualGamepadSettings,
        EJS_Buttons,
        EJS_defaultControls,
        EJS_loadStateURL: string,
        EJS_CacheLimit: number,
        EJS_cacheConfig,
        EJS_cheatPath: string,
        EJS_defaultOptions,
        EJS_gamePatchUrl: string,
        EJS_gameParentUrl: string,
        EJS_netplayServer,
        EJS_netplayICEServers,
        EJS_gameID: string,
        EJS_backgroundImage: string,
        EJS_backgroundBlur,
        EJS_backgroundColor,
        EJS_controlScheme,
        EJS_threads: boolean,
        EJS_disableCue,
        EJS_startButtonName,
        EJS_softLoad,
        EJS_screenCapture,
        EJS_externalFiles,
        EJS_dontExtractRom,
        EJS_dontExtractBIOS,
        EJS_disableLocalStorage: boolean,
        EJS_forceLegacyCores: boolean,
        EJS_noAutoFocus: boolean,
        EJS_videoRotation,
        EJS_hideSettings,
        EJS_browserMode,
        EJS_shaders,
        EJS_fixedSaveInterval,
        EJS_disableAutoUnload,
        EJS_disableBatchBootup;
    }
}