/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameDetailsRouteImport } from './routes/GameDetails'
import { Route as DashboardRouteImport } from './routes/Dashboard'

const GameDetailsRoute = GameDetailsRouteImport.update({
  id: '/GameDetails',
  path: '/GameDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/Dashboard': typeof DashboardRoute
  '/GameDetails': typeof GameDetailsRoute
}
export interface FileRoutesByTo {
  '/Dashboard': typeof DashboardRoute
  '/GameDetails': typeof GameDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/Dashboard': typeof DashboardRoute
  '/GameDetails': typeof GameDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Dashboard' | '/GameDetails'
  fileRoutesByTo: FileRoutesByTo
  to: '/Dashboard' | '/GameDetails'
  id: '__root__' | '/Dashboard' | '/GameDetails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRoute
  GameDetailsRoute: typeof GameDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/GameDetails': {
      id: '/GameDetails'
      path: '/GameDetails'
      fullPath: '/GameDetails'
      preLoaderRoute: typeof GameDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRoute,
  GameDetailsRoute: GameDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
